Add docs on how to configure reports using SAS tokens #859 & Add docs to test/demo reports using Power BI desktop #958
microsoft/finops-toolkit pull request #970
Opened 2024-09-10 10:24 UTC by Zeo-shark

## 🛠️ Description
1. Documented on how to configure reports using SAS tokens #859 
2. Documented how to test/demo '.pbix' reports using Power BI desktop #958

Fixes #859 #958 

## 📋 Checklist

### 🔬 How did you test this change?

> - [ ] 🤏 Lint tests
> - [ ] 🤞 PS -WhatIf / az validate
> - [ ] 👍 Manually deployed + verified
> - [ ] 💪 Unit tests
> - [ ] 🙌 Integration tests

### 🙋‍♀️ Do any of the following that apply?

> - [ ] 🚨 This is a breaking change.
> - [ ] 🤏 The change is less than 20 lines of code.

### 📑 Did you update `docs/changelog.md`?

> - [x] ✅ Updated changelog (required for `dev` PRs)
> - [ ] ➡️ Will add log in a future PR (feature branch PRs only)
> - [ ] ❎ Log not needed (small/internal change)

### 📖 Did you update documentation?

> - [x] ✅ Public docs in `docs` (required for `dev`)
> - [x] ✅ Internal dev docs in `src` (required for `dev`)
> - [ ] ➡️ Will add docs in a future PR (feature branch PRs only)
> - [ ] ❎ Docs not needed (small/internal change)

2024-09-10 10:25 UTC, Zeo-shark commented
Hi @flanakin, @arthurclares,
Somehow my older PR disappeared, and had to create a single PR for both the issues as I wasn't able to create separate PR for separate issues.

2024-09-16 03:51 UTC, Zeo-shark commented
@arthurclares and @flanakin I see there is a merge conflict in the changelog.md can you guide me how do I resolve the same.

2024-09-25 17:11 UTC, flanakin approved these changes

2024-09-25 17:11 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +Use the Shared Access Signature (SAS) token of your FinOps deployment's storage account to setup permissions for the power BI reports. Follow the following steps to setup the power BI dashboards:
```suggestion
Shared Access Signature (SAS) tokens allow you to connect to a storage account without end user credentials or setting up a service principal. To connect Power BI reports to your data via SAS tokens:
```

2024-09-25 17:11 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +1. Generate the Shared Access Signature (SAS) token for storage account to provide required permissions for the power BI dashboards. Follow the steps below:
```suggestion
1. Generate the SAS token with required permissions:
```

2024-09-25 17:11 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![Image representing the SAS token configuration](../../assets/images/aoe/azure-storage-account-SAS.png)
```suggestion
   - Navigate the FinOps hub storage account in the Azure portal.
   - Select **Security + Networking** > **Shared access signature** in the menu on the left.
   - Under **Allowed resource types**, select `Container` and `Object`.
   - Under **Allowed permissions**, select **Read, List**.
   - Provide the start and expiration date range as desired.
   - Keep the remaining default values or update as desired.
   - Select the **Generate SAS token and URL** button.
   - Copy the generated token.
  ![Screenshot of the SAS token configuration in the Azure portal](../../assets/images/aoe/azure-storage-account-SAS.png)
```

2024-09-25 17:11 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![provide the SAS token of your Storage Account to connect to the reports](../../assets/images/aoe/powerbi-dashboard-SAS-token.png)
```suggestion
2. Configure SAS token access in Power BI:
   - Open the report in Power BI Desktop.
   - Select **Transform data** > **Data Source Settings** in the ribbon.
   - Select **Edit permissions** at the bottom of the dialog.
   - Select **Edit** below the credentials.
  ![Screenshot of the data source settings within Transform data](../../assets/images/aoe/powerbi-dashboard-SAS-setup.png)
   - Select the **Shared access signature** tab.
   - Paste the copied SAS token from the Azure portal.
   - Select **Save**.
   - Select **Close**.
   - Select **Apply and Close** in the ribbon.
  ![Screenshot of the SAS token dialog](../../assets/images/aoe/powerbi-dashboard-SAS-token.png)
```

2024-09-25 17:11 UTC, flanakin commented on docs/_resources/changelog.md
> +> 2. Documented how to [visualize/demonstrate the reports using Power BI](../docs/_reporting/hubs/README.md) desktop even without setup required.
```suggestion
📗 FinOps guide
{: .fs-5 .fw-500 .mt-4 mb-0 }

> ➕ Added:
>
> 1. Documented [how to use storage account SAS tokens to setup the reports](../docs/_reporting/power-bi/setup.md).
> 2. Documented how to [preview reports with sample data using Power BI Desktop](../docs/_reporting/hubs/README.md).
```

2024-09-25 17:15 UTC, flanakin commented on docs/_reporting/hubs/README.md
> +![Screenshot of the Rate optimization report with test data](../../assets/images/aoe/rate-optimization-report.png)
We should move this to a hubs folder
```suggestion
![Screenshot of the Rate optimization report with test data](../../assets/images/hubs/rate-optimization-report.png)
```

2024-09-25 17:16 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![Screenshot of the SAS token configuration in the Azure portal](../../assets/images/aoe/azure-storage-account-SAS.png)
```suggestion

  ![Screenshot of the SAS token configuration in the Azure portal](../../assets/images/aoe/azure-storage-account-SAS.png)

```

2024-09-25 17:16 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![Screenshot of the data source settings within Transform data](../../assets/images/aoe/powerbi-dashboard-SAS-setup.png)
```suggestion

  ![Screenshot of the data source settings within Transform data](../../assets/images/aoe/powerbi-dashboard-SAS-setup.png)

```

2024-09-25 17:17 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![Screenshot of the SAS token dialog](../../assets/images/aoe/powerbi-dashboard-SAS-token.png)
```suggestion

  ![Screenshot of the SAS token dialog](../../assets/images/aoe/powerbi-dashboard-SAS-token.png)
```

2024-09-25 17:19 UTC, flanakin commented on docs/_reporting/power-bi/setup.md
> +  ![Screenshot of the SAS token dialog](../../assets/images/aoe/powerbi-dashboard-SAS-token.png)
Move images to hubs folder
```suggestion
  ![Screenshot of the SAS token configuration in the Azure portal](../../assets/images/hubs/azure-storage-account-SAS.png)

2. Configure SAS token access in Power BI:
   - Open the report in Power BI Desktop.
   - Select **Transform data** > **Data Source Settings** in the ribbon.
   - Select **Edit permissions** at the bottom of the dialog.
   - Select **Edit** below the credentials.

  ![Screenshot of the data source settings within Transform data](../../assets/images/hubs/powerbi-dashboard-SAS-setup.png)

   - Select the **Shared access signature** tab.
   - Paste the copied SAS token from the Azure portal.
   - Select **Save**.
   - Select **Close**.
   - Select **Apply and Close** in the ribbon.
  ![Screenshot of the SAS token dialog](../../assets/images/hubs/powerbi-dashboard-SAS-token.png)
```

2024-09-25 17:23 UTC, flanakin requested changes

2024-09-25 17:23 UTC, flanakin commented on docs/assets/images/aoe/releases-folder.png
Delete this file. It doesn't seem to be referenced.

2024-09-25 17:23 UTC, flanakin commented on docs/assets/images/aoe/azure-storage-account-SAS.png
Move all the hubs-specific images to a `assets/images/hubs` folder rather than the existing aoe folder

2024-09-26 14:04 UTC, Zeo-shark commented on docs/assets/images/aoe/azure-storage-account-SAS.png
docs/assets/images/aoe/releases-folder.png is deleted

2024-09-26 14:04 UTC, Zeo-shark commented on docs/assets/images/aoe/releases-folder.png
docs/assets/images/aoe/releases-folder.png is deleted

2024-09-26 14:06 UTC, Zeo-shark commented on docs/assets/images/aoe/azure-storage-account-SAS.png
moved the hub specific images to a separate assets/images/hubs folder, thanks @flanakin

2024-09-26 16:14 UTC, Zeo-shark commented
Additionally added the fix to the issue: [Power BI] Setup doc has broken markup #968

2024-09-27 23:55 UTC, flanakin approved these changes

2024-09-27 23:57 UTC, merged